/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_arun_ndktest_MainActivity.h"

JNIEXPORT jstring JNICALL Java_com_example_arun_ndktest_MainActivity_hello(JNIEnv * env, jobject obj)
{
return (*env)-> NewStringUTF(env,"hello world first app");

}